#!/usr/bin/env bash

if file -- $1 2> /dev/null | grep "Ogg data, Vorbis audio" > /dev/null
then
	cp -- $1 /usr/share/keysound/sounds/english.ogg
else
	echo "change-keysound-english: файл не указан, не найден или недопустимый формат файла" >&2
	exit 1
fi
